# Generated by Django 3.1.2 on 2020-10-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inference',
        ),
    ]
